require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TweetTSProject' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'TweetTSProjectTests' do
    inherit! :complete
    # Pods for testing
  end


end

target 'TweetTSProject-tvOS' do
  # Pods for TweetTSProject-tvOS

  target 'TweetTSProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
